# Theming
font: IosevkaTerm Nerd Font 12
background: "#2e3440ff"
color: "#cdd6f4"
border: "#89b4fb"
separator: " ó°œ¶  "
border_width: 1
corner_r: 0
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: bottom # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: -1
margin_bottom: 200
margin_left: 10
margin_top: 100

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "p"
    desc: "Power Menu"
    submenu:
      - key: "s"
        desc: "Sleep"
        cmd: "systemctl suspend"
      - key: "r"
        desc: "Reboot"
        cmd: "/home/sudhirk/.scripts/sync_poweroff.sh < /home/sudhirk/.scripts/git_folders.txt && reboot"
      - key: "R"
        desc: "Force Reboot"
        cmd: "reboot"
      - key: "p"
        desc: "Poweroff"
        cmd: "/home/sudhirk/.scripts/sync_poweroff.sh < /home/sudhirk/.scripts/git_folders.txt && poweroff"
      - key: "P"
        desc: "Force Poweroff"
        cmd: "poweroff"
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "t"
    desc: "Kitty"
    cmd: "kitty --hold fastfetch"
  - key: "y"
    desc: "Yazi"
    submenu:
      - key: "y"
        desc: "Home"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y; exec zsh\""
      - key: "d"
        desc: "Dotfiles"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/.dotfiles; exec zsh\""
      - key: "c"
        desc: "Config"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/.config; exec zsh\""
      - key: "p"
        desc: "Programming"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/Programming; exec zsh\""
      - key: "L"
        desc: "Lean"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/Programming/Languages; exec zsh\""
      - key: "l"
        desc: "LaTeX"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/LaTeX; exec zsh\""
      - key: "D"
        desc: "Downloads"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/Downloads; exec zsh\""
      - key: "a"
        desc: "Assignments"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && y ~/Programming/ASchoolWork/Assignments; exec zsh\""
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "o"
    desc: "Obsidian"
    submenu:
      - key: "1"
        desc: "PSYC1023"
        cmd: "xdg-open \"obsidian://open?vault=PSYC1023\""
      - key: "2"
        desc: "MATH3063"
        cmd: "xdg-open \"obsidian://open?vault=MATH3063\""
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "d"
    desc: "Vesktop"
    cmd: "vesktop"
  - key: "D"
    desc: "Discordo"
    cmd: "kitty discordo & (sleep 0.3 && /usr/bin/niri-sidebar toggle-window)"
  - key: "N"
    desc: "Notification"
    submenu:
      - key: "t"
        desc: "Toggle SwayNC Panel"
        cmd: "swaync-client -t"
      - key: "d"
        desc: "Toggle DND"
        cmd: "swaync-client -d && notify-send \"DND Enabled: $(swaync-client -D)\""
  - key: "g"
    desc: "Games"
    submenu:
      - key: "h"
        desc: "Heroic Games"
        cmd: "heroic"
      - key: "s"
        desc: "Steam"
        cmd: "steam"
  - key: "n"
    desc: "Neovim"
    submenu:
      - key: "n"
        desc: "Home"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && n; exec zsh\""
      - key: "d"
        desc: "Dotfiles"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && n ~/.dotfiles; exec zsh\""
      - key: "p"
        desc: "Programming"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && n ~/Programming; exec zsh\""
      - key: "L"
        desc: "Lean"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && n ~/Programming/Languages; exec zsh\""
      - key: "l"
        desc: "LaTeX"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && n ~/LaTeX; exec zsh\""
      - key: "a"
        desc: "Assignments"
        cmd: "kitty -e zsh -c \"source ~/.zshrc && n ~/Programming/ASchoolWork/Assignments; exec zsh\""
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "b"
    desc: "Books"
    cmd: "xdg-open $(fd .pdf ~/Books/ | vicinae dmenu -p 'Select Book...')"
  - key: "s"
    desc: "System"
    submenu: 
      - key: "l"
        desc: "Lock Screen"
        cmd: "hyprlock"
      - key: "i"
        desc: "Inhibit Idle"
        cmd: "(pkill hypridle && notify-send 'Disabled Hypridle') || (hypridle & notify-send 'Enabled Hypridle')"
      - key: "W"
        desc: "Toggle Waybar"
        cmd: "(pkill waybar && notify-send 'Disabled Waybar') || (waybar & notify-send 'Enabled Waybar')"
      - key: "w"
        desc: "Toggle Wallpaper"
        cmd: "pkill swaybg || swaybg -i ~/Pictures/Wallpaper-Gargantua.jpg"
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "z"
    desc: "Zen Browser"
    cmd: "zen-twilight"
  - key: "i"
    desc: "Internet"
    submenu: 
      - key: "l"
        desc: "D2L"
        cmd: "xdg-open \"https://lms.unb.ca/d2l/home\""
      - key: "w"
        desc: "Whatsapp"
        cmd: "xdg-open \"https://web.whatsapp.com/\""
      - key: "y"
        desc: "Youtube"
        cmd: "xdg-open \"https://www.youtube.com/\""
      - key: "r"
        desc: "Reddit"
        cmd: "xdg-open \"https://www.reddit.com/\""
      - key: "o"
        desc: "Outlook"
        cmd: "xdg-open \"https://outlook.cloud.microsoft/mail/\""
      - key: "L"
        desc: "Loogle"
        cmd: "xdg-open \"https://loogle.lean-lang.org/\""
      - key: "d"
        desc: "Desmos"
        cmd: "xdg-open \"https://www.desmos.com/calculator\""
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "G"
    desc: "Git"
    submenu:
      - key: "d"
        desc: "Dotfiles"
        cmd: "kitty -e zsh -c \"cd ~/.backups/dotfiles && ./copy.sh\""
      - key: "a"
        desc: "Assignments"
        cmd: "kitty -e zsh -c \"cd ~/Programming/ASchoolWork/Assignments && lazygit\""
      - key: "l"
        desc: "LaTeX"
        cmd: "kitty -e zsh -c \"cd ~/LaTeX && lazygit\""
      - key: "q"
        desc: "Quit"
        cmd: ""
  - key: "f"
    desc: "Nautilus"
    cmd: "nautilus"
  - key: "B"
    desc: "Btop"
    cmd: "kitty btop"
  - key: "v"
    desc: "Vicinae"
    cmd: "vicinae toggle"
  - key: "Q"
    desc: "Close Window"
    cmd: "niri msg action close-window"
  - key: "q"
    desc: "Quit"
    cmd: ""

